# Multiple Linear Regression

## Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing the dataset

In [2]:
dataset = pd.read_csv("ANZ_customers_salary.csv")
X = dataset.iloc[:, [2, 4]].values
y = dataset.iloc[:, 3].values

In [3]:
print(X)

[[40 'South Australia']
 [38 'Victoria']
 [43 'Victoria']
 [78 'Victoria']
 [26 'Western Australia']
 [25 'Queensland']
 [38 'South Australia']
 [52 'Western Australia']
 [42 'Queensland']
 [26 'New South Wales']
 [18 'Queensland']
 [39 'New South Wales']
 [33 'Victoria']
 [35 'New South Wales']
 [19 'Victoria']
 [28 'New South Wales']
 [20 'South Australia']
 [42 'Australian Capital Territory']
 [18 'South Australia']
 [20 'Victoria']
 [26 'Queensland']
 [22 'New South Wales']
 [28 'Victoria']
 [19 'Western Australia']
 [50 'Victoria']
 [43 'Victoria']
 [22 'New South Wales']
 [42 'Victoria']
 [19 'New South Wales']
 [42 'New South Wales']
 [41 'Victoria']
 [23 'New South Wales']
 [30 'South Australia']
 [28 'Queensland']
 [30 'Queensland']
 [24 'Victoria']
 [21 'Northern Territory']
 [34 'South Australia']
 [38 'Northern Territory']
 [37 'Queensland']
 [21 'Victoria']
 [21 'Western Australia']
 [26 'New South Wales']
 [29 'Western Australia']
 [35 'Queensland']
 [27 'Victoria']
 [24 

In [4]:
X = X.reshape(X.shape[0],-1)

## Encoding Categorical Variable

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse=False), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [6]:
print(X)

[[0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 40]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 38]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 43]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 78]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 26]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 25]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 38]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 52]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 42]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 26]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 18]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 39]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 33]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 35]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 19]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 28]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 20]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 42]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 18]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 20]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 26]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 22]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 28]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 19]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 50]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 43]
 [0.0 1.0 0.

## Splitting the dataset into Training Set and Test Set

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [8]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [9]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[2292.53  983.36]
 [2408.75 3517.61]
 [2018.78 1630.36]
 [2759.    862.95]
 [2337.32 2218.73]
 [2893.84 1225.33]
 [2986.53 3026.95]
 [2094.63 1541.12]
 [2353.21 1952.29]
 [2367.66 1640.83]
 [2261.48 1396.23]
 [2382.82 2485.37]
 [2018.78 2588.01]
 [2095.35 2308.67]
 [2484.29 3785.78]
 [2049.12 2101.51]
 [2246.31 1916.51]
 [1912.61 1436.98]
 [2469.43 2538.68]
 [2257.08 3231.26]]


## Applying K-fold Cross-Validation

In [10]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(regressor, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: -39.55 %
Standard Deviation: 63.91 %
